# Generated by Django 2.2.6 on 2019-10-14 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('external_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('payee_note', models.TextField()),
                ('payer_message', models.TextField()),
                ('payer_party_id_type', models.CharField(max_length=100)),
                ('payer_party_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('financial_transaction_id', models.CharField(max_length=255)),
            ],
        ),
    ]
